[package]
name = "typed-api"
version = "0.1.0"
authors = ["valtena <ethanvaltena@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openapiv3 = "0.3.2"
serde_json = "1.0.61"
indexmap = "1.0.0"
